// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/protobuf.proto

package com.holland.kit.netty.protobuf;

public interface CatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.holland.kit.netty.protobuf.Cat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string city = 2;</code>
   * @return Whether the city field is set.
   */
  boolean hasCity();
  /**
   * <code>optional string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
