// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/protobuf.proto

package com.holland.kit.netty.protobuf;

/**
 * Protobuf type {@code com.holland.kit.netty.protobuf.Msg}
 */
public final class Msg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.holland.kit.netty.protobuf.Msg)
    MsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Msg.newBuilder() to construct.
  private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Msg() {
    dataType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Msg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.holland.kit.netty.protobuf.Protobuf.internal_static_com_holland_kit_netty_protobuf_Msg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.holland.kit.netty.protobuf.Protobuf.internal_static_com_holland_kit_netty_protobuf_Msg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.holland.kit.netty.protobuf.Msg.class, com.holland.kit.netty.protobuf.Msg.Builder.class);
  }

  /**
   * Protobuf enum {@code com.holland.kit.netty.protobuf.Msg.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PersonType = 0;</code>
     */
    PersonType(0),
    /**
     * <code>DogType = 1;</code>
     */
    DogType(1),
    /**
     * <code>CatType = 2;</code>
     */
    CatType(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PersonType = 0;</code>
     */
    public static final int PersonType_VALUE = 0;
    /**
     * <code>DogType = 1;</code>
     */
    public static final int DogType_VALUE = 1;
    /**
     * <code>CatType = 2;</code>
     */
    public static final int CatType_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return PersonType;
        case 1: return DogType;
        case 2: return CatType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.holland.kit.netty.protobuf.Msg.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.holland.kit.netty.protobuf.Msg.DataType)
  }

  private int dataBodyCase_ = 0;
  private java.lang.Object dataBody_;
  public enum DataBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PERSON(2),
    DOG(3),
    CAT(4),
    DATABODY_NOT_SET(0);
    private final int value;
    private DataBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataBodyCase forNumber(int value) {
      switch (value) {
        case 2: return PERSON;
        case 3: return DOG;
        case 4: return CAT;
        case 0: return DATABODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataBodyCase
  getDataBodyCase() {
    return DataBodyCase.forNumber(
        dataBodyCase_);
  }

  public static final int DATA_TYPE_FIELD_NUMBER = 1;
  private int dataType_;
  /**
   * <pre>
   *用于表示当前传递的类型
   * </pre>
   *
   * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  @java.lang.Override public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <pre>
   *用于表示当前传递的类型
   * </pre>
   *
   * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
   * @return The dataType.
   */
  @java.lang.Override public com.holland.kit.netty.protobuf.Msg.DataType getDataType() {
    @SuppressWarnings("deprecation")
    com.holland.kit.netty.protobuf.Msg.DataType result = com.holland.kit.netty.protobuf.Msg.DataType.valueOf(dataType_);
    return result == null ? com.holland.kit.netty.protobuf.Msg.DataType.UNRECOGNIZED : result;
  }

  public static final int PERSON_FIELD_NUMBER = 2;
  /**
   * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
   * @return Whether the person field is set.
   */
  @java.lang.Override
  public boolean hasPerson() {
    return dataBodyCase_ == 2;
  }
  /**
   * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
   * @return The person.
   */
  @java.lang.Override
  public com.holland.kit.netty.protobuf.Person getPerson() {
    if (dataBodyCase_ == 2) {
       return (com.holland.kit.netty.protobuf.Person) dataBody_;
    }
    return com.holland.kit.netty.protobuf.Person.getDefaultInstance();
  }
  /**
   * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
   */
  @java.lang.Override
  public com.holland.kit.netty.protobuf.PersonOrBuilder getPersonOrBuilder() {
    if (dataBodyCase_ == 2) {
       return (com.holland.kit.netty.protobuf.Person) dataBody_;
    }
    return com.holland.kit.netty.protobuf.Person.getDefaultInstance();
  }

  public static final int DOG_FIELD_NUMBER = 3;
  /**
   * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
   * @return Whether the dog field is set.
   */
  @java.lang.Override
  public boolean hasDog() {
    return dataBodyCase_ == 3;
  }
  /**
   * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
   * @return The dog.
   */
  @java.lang.Override
  public com.holland.kit.netty.protobuf.Dog getDog() {
    if (dataBodyCase_ == 3) {
       return (com.holland.kit.netty.protobuf.Dog) dataBody_;
    }
    return com.holland.kit.netty.protobuf.Dog.getDefaultInstance();
  }
  /**
   * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
   */
  @java.lang.Override
  public com.holland.kit.netty.protobuf.DogOrBuilder getDogOrBuilder() {
    if (dataBodyCase_ == 3) {
       return (com.holland.kit.netty.protobuf.Dog) dataBody_;
    }
    return com.holland.kit.netty.protobuf.Dog.getDefaultInstance();
  }

  public static final int CAT_FIELD_NUMBER = 4;
  /**
   * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
   * @return Whether the cat field is set.
   */
  @java.lang.Override
  public boolean hasCat() {
    return dataBodyCase_ == 4;
  }
  /**
   * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
   * @return The cat.
   */
  @java.lang.Override
  public com.holland.kit.netty.protobuf.Cat getCat() {
    if (dataBodyCase_ == 4) {
       return (com.holland.kit.netty.protobuf.Cat) dataBody_;
    }
    return com.holland.kit.netty.protobuf.Cat.getDefaultInstance();
  }
  /**
   * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
   */
  @java.lang.Override
  public com.holland.kit.netty.protobuf.CatOrBuilder getCatOrBuilder() {
    if (dataBodyCase_ == 4) {
       return (com.holland.kit.netty.protobuf.Cat) dataBody_;
    }
    return com.holland.kit.netty.protobuf.Cat.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataType_ != com.holland.kit.netty.protobuf.Msg.DataType.PersonType.getNumber()) {
      output.writeEnum(1, dataType_);
    }
    if (dataBodyCase_ == 2) {
      output.writeMessage(2, (com.holland.kit.netty.protobuf.Person) dataBody_);
    }
    if (dataBodyCase_ == 3) {
      output.writeMessage(3, (com.holland.kit.netty.protobuf.Dog) dataBody_);
    }
    if (dataBodyCase_ == 4) {
      output.writeMessage(4, (com.holland.kit.netty.protobuf.Cat) dataBody_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataType_ != com.holland.kit.netty.protobuf.Msg.DataType.PersonType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dataType_);
    }
    if (dataBodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.holland.kit.netty.protobuf.Person) dataBody_);
    }
    if (dataBodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.holland.kit.netty.protobuf.Dog) dataBody_);
    }
    if (dataBodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.holland.kit.netty.protobuf.Cat) dataBody_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.holland.kit.netty.protobuf.Msg)) {
      return super.equals(obj);
    }
    com.holland.kit.netty.protobuf.Msg other = (com.holland.kit.netty.protobuf.Msg) obj;

    if (dataType_ != other.dataType_) return false;
    if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
    switch (dataBodyCase_) {
      case 2:
        if (!getPerson()
            .equals(other.getPerson())) return false;
        break;
      case 3:
        if (!getDog()
            .equals(other.getDog())) return false;
        break;
      case 4:
        if (!getCat()
            .equals(other.getCat())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    switch (dataBodyCase_) {
      case 2:
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPerson().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DOG_FIELD_NUMBER;
        hash = (53 * hash) + getDog().hashCode();
        break;
      case 4:
        hash = (37 * hash) + CAT_FIELD_NUMBER;
        hash = (53 * hash) + getCat().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.holland.kit.netty.protobuf.Msg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.holland.kit.netty.protobuf.Msg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.holland.kit.netty.protobuf.Msg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.holland.kit.netty.protobuf.Msg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.holland.kit.netty.protobuf.Msg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.holland.kit.netty.protobuf.Msg)
      com.holland.kit.netty.protobuf.MsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.holland.kit.netty.protobuf.Protobuf.internal_static_com_holland_kit_netty_protobuf_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.holland.kit.netty.protobuf.Protobuf.internal_static_com_holland_kit_netty_protobuf_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.holland.kit.netty.protobuf.Msg.class, com.holland.kit.netty.protobuf.Msg.Builder.class);
    }

    // Construct using com.holland.kit.netty.protobuf.Msg.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataType_ = 0;

      if (personBuilder_ != null) {
        personBuilder_.clear();
      }
      if (dogBuilder_ != null) {
        dogBuilder_.clear();
      }
      if (catBuilder_ != null) {
        catBuilder_.clear();
      }
      dataBodyCase_ = 0;
      dataBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.holland.kit.netty.protobuf.Protobuf.internal_static_com_holland_kit_netty_protobuf_Msg_descriptor;
    }

    @java.lang.Override
    public com.holland.kit.netty.protobuf.Msg getDefaultInstanceForType() {
      return com.holland.kit.netty.protobuf.Msg.getDefaultInstance();
    }

    @java.lang.Override
    public com.holland.kit.netty.protobuf.Msg build() {
      com.holland.kit.netty.protobuf.Msg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.holland.kit.netty.protobuf.Msg buildPartial() {
      com.holland.kit.netty.protobuf.Msg result = new com.holland.kit.netty.protobuf.Msg(this);
      result.dataType_ = dataType_;
      if (dataBodyCase_ == 2) {
        if (personBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = personBuilder_.build();
        }
      }
      if (dataBodyCase_ == 3) {
        if (dogBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = dogBuilder_.build();
        }
      }
      if (dataBodyCase_ == 4) {
        if (catBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = catBuilder_.build();
        }
      }
      result.dataBodyCase_ = dataBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.holland.kit.netty.protobuf.Msg) {
        return mergeFrom((com.holland.kit.netty.protobuf.Msg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.holland.kit.netty.protobuf.Msg other) {
      if (other == com.holland.kit.netty.protobuf.Msg.getDefaultInstance()) return this;
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      switch (other.getDataBodyCase()) {
        case PERSON: {
          mergePerson(other.getPerson());
          break;
        }
        case DOG: {
          mergeDog(other.getDog());
          break;
        }
        case CAT: {
          mergeCat(other.getCat());
          break;
        }
        case DATABODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              dataType_ = input.readEnum();

              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getPersonFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataBodyCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDogFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataBodyCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getCatFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataBodyCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public DataBodyCase
        getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public Builder clearDataBody() {
      dataBodyCase_ = 0;
      dataBody_ = null;
      onChanged();
      return this;
    }


    private int dataType_ = 0;
    /**
     * <pre>
     *用于表示当前传递的类型
     * </pre>
     *
     * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *用于表示当前传递的类型
     * </pre>
     *
     * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
     * @param value The enum numeric value on the wire for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeValue(int value) {
      
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用于表示当前传递的类型
     * </pre>
     *
     * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.Msg.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.holland.kit.netty.protobuf.Msg.DataType result = com.holland.kit.netty.protobuf.Msg.DataType.valueOf(dataType_);
      return result == null ? com.holland.kit.netty.protobuf.Msg.DataType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *用于表示当前传递的类型
     * </pre>
     *
     * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(com.holland.kit.netty.protobuf.Msg.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用于表示当前传递的类型
     * </pre>
     *
     * <code>.com.holland.kit.netty.protobuf.Msg.DataType data_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {
      
      dataType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.holland.kit.netty.protobuf.Person, com.holland.kit.netty.protobuf.Person.Builder, com.holland.kit.netty.protobuf.PersonOrBuilder> personBuilder_;
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     * @return The person.
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.Person getPerson() {
      if (personBuilder_ == null) {
        if (dataBodyCase_ == 2) {
          return (com.holland.kit.netty.protobuf.Person) dataBody_;
        }
        return com.holland.kit.netty.protobuf.Person.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 2) {
          return personBuilder_.getMessage();
        }
        return com.holland.kit.netty.protobuf.Person.getDefaultInstance();
      }
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    public Builder setPerson(com.holland.kit.netty.protobuf.Person value) {
      if (personBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        personBuilder_.setMessage(value);
      }
      dataBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    public Builder setPerson(
        com.holland.kit.netty.protobuf.Person.Builder builderForValue) {
      if (personBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        personBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    public Builder mergePerson(com.holland.kit.netty.protobuf.Person value) {
      if (personBuilder_ == null) {
        if (dataBodyCase_ == 2 &&
            dataBody_ != com.holland.kit.netty.protobuf.Person.getDefaultInstance()) {
          dataBody_ = com.holland.kit.netty.protobuf.Person.newBuilder((com.holland.kit.netty.protobuf.Person) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 2) {
          personBuilder_.mergeFrom(value);
        } else {
          personBuilder_.setMessage(value);
        }
      }
      dataBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    public Builder clearPerson() {
      if (personBuilder_ == null) {
        if (dataBodyCase_ == 2) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 2) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        personBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    public com.holland.kit.netty.protobuf.Person.Builder getPersonBuilder() {
      return getPersonFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.PersonOrBuilder getPersonOrBuilder() {
      if ((dataBodyCase_ == 2) && (personBuilder_ != null)) {
        return personBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 2) {
          return (com.holland.kit.netty.protobuf.Person) dataBody_;
        }
        return com.holland.kit.netty.protobuf.Person.getDefaultInstance();
      }
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Person person = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.holland.kit.netty.protobuf.Person, com.holland.kit.netty.protobuf.Person.Builder, com.holland.kit.netty.protobuf.PersonOrBuilder> 
        getPersonFieldBuilder() {
      if (personBuilder_ == null) {
        if (!(dataBodyCase_ == 2)) {
          dataBody_ = com.holland.kit.netty.protobuf.Person.getDefaultInstance();
        }
        personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.holland.kit.netty.protobuf.Person, com.holland.kit.netty.protobuf.Person.Builder, com.holland.kit.netty.protobuf.PersonOrBuilder>(
                (com.holland.kit.netty.protobuf.Person) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 2;
      onChanged();;
      return personBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.holland.kit.netty.protobuf.Dog, com.holland.kit.netty.protobuf.Dog.Builder, com.holland.kit.netty.protobuf.DogOrBuilder> dogBuilder_;
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     * @return Whether the dog field is set.
     */
    @java.lang.Override
    public boolean hasDog() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     * @return The dog.
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.Dog getDog() {
      if (dogBuilder_ == null) {
        if (dataBodyCase_ == 3) {
          return (com.holland.kit.netty.protobuf.Dog) dataBody_;
        }
        return com.holland.kit.netty.protobuf.Dog.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 3) {
          return dogBuilder_.getMessage();
        }
        return com.holland.kit.netty.protobuf.Dog.getDefaultInstance();
      }
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    public Builder setDog(com.holland.kit.netty.protobuf.Dog value) {
      if (dogBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        dogBuilder_.setMessage(value);
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    public Builder setDog(
        com.holland.kit.netty.protobuf.Dog.Builder builderForValue) {
      if (dogBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        dogBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    public Builder mergeDog(com.holland.kit.netty.protobuf.Dog value) {
      if (dogBuilder_ == null) {
        if (dataBodyCase_ == 3 &&
            dataBody_ != com.holland.kit.netty.protobuf.Dog.getDefaultInstance()) {
          dataBody_ = com.holland.kit.netty.protobuf.Dog.newBuilder((com.holland.kit.netty.protobuf.Dog) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 3) {
          dogBuilder_.mergeFrom(value);
        } else {
          dogBuilder_.setMessage(value);
        }
      }
      dataBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    public Builder clearDog() {
      if (dogBuilder_ == null) {
        if (dataBodyCase_ == 3) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 3) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        dogBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    public com.holland.kit.netty.protobuf.Dog.Builder getDogBuilder() {
      return getDogFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.DogOrBuilder getDogOrBuilder() {
      if ((dataBodyCase_ == 3) && (dogBuilder_ != null)) {
        return dogBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 3) {
          return (com.holland.kit.netty.protobuf.Dog) dataBody_;
        }
        return com.holland.kit.netty.protobuf.Dog.getDefaultInstance();
      }
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Dog dog = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.holland.kit.netty.protobuf.Dog, com.holland.kit.netty.protobuf.Dog.Builder, com.holland.kit.netty.protobuf.DogOrBuilder> 
        getDogFieldBuilder() {
      if (dogBuilder_ == null) {
        if (!(dataBodyCase_ == 3)) {
          dataBody_ = com.holland.kit.netty.protobuf.Dog.getDefaultInstance();
        }
        dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.holland.kit.netty.protobuf.Dog, com.holland.kit.netty.protobuf.Dog.Builder, com.holland.kit.netty.protobuf.DogOrBuilder>(
                (com.holland.kit.netty.protobuf.Dog) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 3;
      onChanged();;
      return dogBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.holland.kit.netty.protobuf.Cat, com.holland.kit.netty.protobuf.Cat.Builder, com.holland.kit.netty.protobuf.CatOrBuilder> catBuilder_;
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     * @return Whether the cat field is set.
     */
    @java.lang.Override
    public boolean hasCat() {
      return dataBodyCase_ == 4;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     * @return The cat.
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.Cat getCat() {
      if (catBuilder_ == null) {
        if (dataBodyCase_ == 4) {
          return (com.holland.kit.netty.protobuf.Cat) dataBody_;
        }
        return com.holland.kit.netty.protobuf.Cat.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 4) {
          return catBuilder_.getMessage();
        }
        return com.holland.kit.netty.protobuf.Cat.getDefaultInstance();
      }
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    public Builder setCat(com.holland.kit.netty.protobuf.Cat value) {
      if (catBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        catBuilder_.setMessage(value);
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    public Builder setCat(
        com.holland.kit.netty.protobuf.Cat.Builder builderForValue) {
      if (catBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        catBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    public Builder mergeCat(com.holland.kit.netty.protobuf.Cat value) {
      if (catBuilder_ == null) {
        if (dataBodyCase_ == 4 &&
            dataBody_ != com.holland.kit.netty.protobuf.Cat.getDefaultInstance()) {
          dataBody_ = com.holland.kit.netty.protobuf.Cat.newBuilder((com.holland.kit.netty.protobuf.Cat) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 4) {
          catBuilder_.mergeFrom(value);
        } else {
          catBuilder_.setMessage(value);
        }
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    public Builder clearCat() {
      if (catBuilder_ == null) {
        if (dataBodyCase_ == 4) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 4) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        catBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    public com.holland.kit.netty.protobuf.Cat.Builder getCatBuilder() {
      return getCatFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    @java.lang.Override
    public com.holland.kit.netty.protobuf.CatOrBuilder getCatOrBuilder() {
      if ((dataBodyCase_ == 4) && (catBuilder_ != null)) {
        return catBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 4) {
          return (com.holland.kit.netty.protobuf.Cat) dataBody_;
        }
        return com.holland.kit.netty.protobuf.Cat.getDefaultInstance();
      }
    }
    /**
     * <code>.com.holland.kit.netty.protobuf.Cat cat = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.holland.kit.netty.protobuf.Cat, com.holland.kit.netty.protobuf.Cat.Builder, com.holland.kit.netty.protobuf.CatOrBuilder> 
        getCatFieldBuilder() {
      if (catBuilder_ == null) {
        if (!(dataBodyCase_ == 4)) {
          dataBody_ = com.holland.kit.netty.protobuf.Cat.getDefaultInstance();
        }
        catBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.holland.kit.netty.protobuf.Cat, com.holland.kit.netty.protobuf.Cat.Builder, com.holland.kit.netty.protobuf.CatOrBuilder>(
                (com.holland.kit.netty.protobuf.Cat) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 4;
      onChanged();;
      return catBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.holland.kit.netty.protobuf.Msg)
  }

  // @@protoc_insertion_point(class_scope:com.holland.kit.netty.protobuf.Msg)
  private static final com.holland.kit.netty.protobuf.Msg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.holland.kit.netty.protobuf.Msg();
  }

  public static com.holland.kit.netty.protobuf.Msg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Msg>
      PARSER = new com.google.protobuf.AbstractParser<Msg>() {
    @java.lang.Override
    public Msg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Msg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Msg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.holland.kit.netty.protobuf.Msg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

