// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/protobuf.proto

package com.holland.kit.netty.protobuf;

public final class Protobuf {
  private Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_holland_kit_netty_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_holland_kit_netty_protobuf_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_holland_kit_netty_protobuf_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_holland_kit_netty_protobuf_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_holland_kit_netty_protobuf_Dog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_holland_kit_netty_protobuf_Dog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_holland_kit_netty_protobuf_Cat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_holland_kit_netty_protobuf_Cat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035main/resources/protobuf.proto\022\036com.hol" +
      "land.kit.netty.protobuf\"\252\002\n\003Msg\022?\n\tdata_" +
      "type\030\001 \001(\0162,.com.holland.kit.netty.proto" +
      "buf.Msg.DataType\0228\n\006person\030\002 \001(\0132&.com.h" +
      "olland.kit.netty.protobuf.PersonH\000\0222\n\003do" +
      "g\030\003 \001(\0132#.com.holland.kit.netty.protobuf" +
      ".DogH\000\0222\n\003cat\030\004 \001(\0132#.com.holland.kit.ne" +
      "tty.protobuf.CatH\000\"4\n\010DataType\022\016\n\nPerson" +
      "Type\020\000\022\013\n\007DogType\020\001\022\013\n\007CatType\020\002B\n\n\010data" +
      "Body\"`\n\006Person\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\020\n\003age" +
      "\030\002 \001(\005H\001\210\001\001\022\024\n\007address\030\003 \001(\tH\002\210\001\001B\007\n\005_na" +
      "meB\006\n\004_ageB\n\n\010_address\";\n\003Dog\022\021\n\004name\030\001 " +
      "\001(\tH\000\210\001\001\022\020\n\003age\030\002 \001(\005H\001\210\001\001B\007\n\005_nameB\006\n\004_" +
      "age\"=\n\003Cat\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\021\n\004city\030\002 " +
      "\001(\tH\001\210\001\001B\007\n\005_nameB\007\n\005_cityB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_holland_kit_netty_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_holland_kit_netty_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_holland_kit_netty_protobuf_Msg_descriptor,
        new java.lang.String[] { "DataType", "Person", "Dog", "Cat", "DataBody", });
    internal_static_com_holland_kit_netty_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_holland_kit_netty_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_holland_kit_netty_protobuf_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", "Name", "Age", "Address", });
    internal_static_com_holland_kit_netty_protobuf_Dog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_holland_kit_netty_protobuf_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_holland_kit_netty_protobuf_Dog_descriptor,
        new java.lang.String[] { "Name", "Age", "Name", "Age", });
    internal_static_com_holland_kit_netty_protobuf_Cat_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_holland_kit_netty_protobuf_Cat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_holland_kit_netty_protobuf_Cat_descriptor,
        new java.lang.String[] { "Name", "City", "Name", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
